import falling from "./assets/dataLogos/falling.jpg";
import lost from "./assets/dataLogos/lost.jpg";
import spirits from "./assets/dataLogos/spirits.jpg";
import follet from "./assets/dataLogos/follett.jpg";
import hike from "./assets/dataLogos/hike.jpg";
import spy from "./assets/dataLogos/spy.jpg";
import midnight from "./assets/dataLogos/midnight.jpg";
import sanctioned from "./assets/dataLogos/sanctioned.jpg";
import ugly from "./assets/dataLogos/ugly.jpg";
import cannot from "./assets/dataLogos/cannot-see.jpg";
import girl from "./assets/dataLogos/girl.jpg";
import mad from "./assets/dataLogos/mad.jpg";



export const DataBase = [
  {
    pathname: "dark-space",
    author: "Buster Hymen",
    genres: ["Horror", "History", "Biography"],
    id: 0,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling7.jpg",
    name: "Dark Space",
    price: 50,
    rating: 6.5,
    review: 120,
  },
  {
    pathname: "red-planet",
    author: "Otto Matic",
    genres: ["Thriller", "Science Fiction", "Biography"],
    id: 1,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling8.jpg",
    name: "Red Planet",
    price: 35,
    rating: 5.5,
    review: 115,
  },
  {
    pathname: "independet",
    author: "Juan Annatoo",
    genres: ["Love Story", "History", "Biography"],
    id: 2,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling6.jpg",
    name: "Independent",
    price: 75,
    rating: 8,
    review: 200,
  },
  {
    pathname: "queen-bee",
    author: "Cam L. Toe",
    genres: ["History", "Science Fiction"],
    id: 3,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling4.jpg",
    name: "Queen Bee",
    price: 40,
    rating: 6.5,
    review: 111,
  },
  {
    pathname: "the-good-guy",
    author: "Juan Annatoo",
    genres: ["Horror"],
    id: 4,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling9.jpg.webp",
    name: "The Good Guy",
    price: 80,
    rating: 8.5,
    review: 194,
  },
  {
    pathname: "very-nice",
    author: "Phil Harmonic",
    genres: ["Love Story", "History"],
    id: 5,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling2.jpg",
    name: "Very Nice",
    price: 25,
    rating: 3.5,
    review: 131,
  },
  {
    pathname: "the-lighting",
    author: "Otto Matic",
    genres: ["Bioghraphy", "Love Story"],
    id: 6,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/hero/h1_hero2.jpg",
    name: "The Lightning",
    price: 37,
    rating: 4,
    review: 100,
  },
  {
    pathname: "evanesce",
    author: "Buster Hyman",
    genres: ["Horror", "Thriller"],
    id: 7,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling3.jpg",
    name: "Evanesce",
    price: 48,
    rating: 5,
    review: 173,
  },
  {
    pathname: "Mad",
    author: "Cam L. Toe",
    genres: ["Horror", "Love Story"],
    id: 8,
    img: `${mad}`,
    name: "Mad",
    price: 75,
    rating: 7,
    review: 233,
  },
  {
    pathname: "Falling",
    author: "Juan Annatoo",
    genres: ["Biography", "Science Fiction", "History"],
    id: 9,
    img: `${falling}`,
    name: "Falling",
    price: 47,
    rating: 5,
    review: 122,
  },
  {
    pathname: "Lost",
    author: "Buster Hyman",
    genres: ["History", "Biography"],
    id: 10,
    img: `${lost}`,
    name: "Lost",
    price: 88,
    rating: 8.5,
    review: 341,
  },
  {
    pathname: "spirits",
    author: "Phil Harmonic",
    genres: ["Horror", "Thriller"],
    id: 11,
    img: `${spirits}`,
    name: "Spirits",
    price: 64,
    rating: 6,
    review: 143,
  },
  {
    pathname: "follet",
    author: "Otto Matic",
    genres: ["Horror", "Love Story"],
    id: 12,
    img: `${follet}`,
    name: "Follet",
    price: 150,
    rating: 10,
    review: 555,
  },
  {
    pathname: "hike",
    author: "Juan Annatoo",
    genres: ["History", "Biography"],
    id: 13,
    img: `${hike}`,
    name: "Hike",
    price: 99,
    rating: 9.5,
    review: 320,
  },
  {
    pathname: "spy",
    author: "Cam L. Toe",
    genres: ["Biography", "Love Story"],
    id: 14,
    img: `${spy}`,
    name: "Spy",
    price: 69,
    rating: 7,
    review: 153,
  },
  {
    pathname: "midnight",
    author: "Buster Hyman",
    genres: ["Horror", "Thriller"],
    id: 15,
    img: `${midnight}`,
    name: "Midnight",
    price: 77,
    rating: 8.5,
    review: 234,
  },
  {
    pathname: "sanctioned",
    author: "Phil Harmonic",
    genres: ["Biography", "Thriller"],
    id: 16,
    img: `${sanctioned}`,
    name: "Sanctioned",
    price: 32,
    rating: 3.2,
    review: 103,
  },
  {
    pathname: "ugly",
    author: "Otto Matic",
    genres: ["Horror", "Biography"],
    id: 17,
    img: `${ugly}`,
    name: "Ugly",
    price: 72,
    rating: 5.5,
    review: 167,
  },
  {
    pathname: "Cannot See",
    author: "Juan Annatoo",
    genres: ["Thriller", "Biography"],
    id: 18,
    img: `${cannot}`,
    name: "Cannot See",
    price: 100,
    rating: 9.5,
    review: 129,
  },
  {
    pathname: "moon-dance",
    author: "Cam L. Toe",
    genres: ["Horror", "Biography"],
    id: 19,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling1.jpg",
    name: "Moon Dance",
    price: 86,
    rating: 6,
    review: 130,
  },
  {
    pathname: "girl",
    author: "Buster Hyman",
    genres: ["Horror", "Love Story"],
    id: 20,
    img: `${girl}`,
    name: "Girl",
    price: 150,
    rating: 10,
    review: 134,
  },
];

export type MovieType = {
  pathname: string;
  author: string;
  genres: string[];
  id: number;
  img: string;
  name: string;
  price: number;
  rating: number;
  review: number;
};
