export const DataBase = [
  {
    pathname: "dark-space",
    author: "Buster Hymen",
    genres: ["Horror", "History", "Biography"],
    id: 0,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling7.jpg",
    name: "Dark Space",
    price: 50,
    rating: 6.5,
    review: 120,
  },
  {
    pathname: "red-planet",
    author: "Otto Matic",
    genres: ["Thriller", "Science Fiction", "Biography"],
    id: 1,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling8.jpg",
    name: "Red Planet",
    price: 35,
    rating: 5.5,
    review: 115,
  },
  {
    pathname: "independet",
    author: "Juan Annatoo",
    genres: ["Love Story", "History", "Biography"],
    id: 2,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling6.jpg",
    name: "Independent",
    price: 75,
    rating: 8,
    review: 200,
  },
  {
    pathname: "queen-bee",
    author: "Cam L. Toe",
    genres: ["History", "Science Fiction"],
    id: 3,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling4.jpg",
    name: "Queen Bee",
    price: 40,
    rating: 6.5,
    review: 111,
  },
  {
    pathname: "the-good-guy",
    author: "Juan Annatoo",
    genres: ["Horror"],
    id: 4,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling9.jpg.webp",
    name: "The Good Guy",
    price: 80,
    rating: 8.5,
    review: 194,
  },
  {
    pathname: "very-nice",
    author: "Phil Harmonic",
    genres: ["Love Story", "History"],
    id: 5,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling2.jpg",
    name: "Very Nice",
    price: 25,
    rating: 3.5,
    review: 131,
  },
  {
    pathname: "the-lighting",
    author: "Otto Matic",
    genres: ["Bioghraphy", "Love Story"],
    id: 6,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/hero/h1_hero2.jpg",
    name: "The Lightning",
    price: 37,
    rating: 4,
    review: 100,
  },
  {
    pathname: "evanesce",
    author: "Buster Hyman",
    genres: ["Horror", "Thriller"],
    id: 7,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling3.jpg",
    name: "Evanesce",
    price: 48,
    rating: 5,
    review: 173,
  },
  {
    pathname: "italian-bones",
    author: "Cam L. Toe",
    genres: ["Horror", "Love Story"],
    id: 8,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/hero/h1_hero3.jpg",
    name: "Italian Bones",
    price: 75,
    rating: 7,
    review: 233,
  },
  {
    pathname: "biba",
    author: "Juan Annatoo",
    genres: ["Biography", "Science Fiction", "History"],
    id: 9,
    img: "https://i0.wp.com/bestindiebookaward.com/submit/wp-content/uploads/2019/08/1632344486b.png?fit=1500%2C1500&ssl=1",
    name: "BIBA",
    price: 47,
    rating: 5,
    review: 122,
  },
  {
    pathname: "this-way-up",
    author: "Buster Hyman",
    genres: ["History", "Biography"],
    id: 10,
    img: "https://payload.cargocollective.com/1/0/8590/5114288/This-Way-Up.png",
    name: "This Way Up",
    price: 88,
    rating: 8.5,
    review: 341,
  },
  {
    pathname: "this-way-down",
    author: "Phil Harmonic",
    genres: ["Horror", "Thriller"],
    id: 11,
    img: "https://elephantbookstore.com/image/cache/catalog/Books/Non-Fiction/Dzheyms-Knap--Sprint-53000-0-950x950.png",
    name: "This Way Down",
    price: 64,
    rating: 6,
    review: 143,
  },
  {
    pathname: "the-murder",
    author: "Otto Matic",
    genres: ["Horror", "Love Story"],
    id: 12,
    img: "	https://preview.colorlib.com/theme/abcbook/assets/img/hero/h1_hero1.jpg",
    name: "The Murder",
    price: 150,
    rating: 10,
    review: 555,
  },
  {
    pathname: "google-ads",
    author: "Juan Annatoo",
    genres: ["History", "Biography"],
    id: 13,
    img: "https://d1aettbyeyfilo.cloudfront.net/simplyconverting/16577697_1611813091417Google_Ads_Cheatsheet_Cover_Ver_1.png",
    name: "Google ADS",
    price: 99,
    rating: 9.5,
    review: 320,
  },
  {
    pathname: "take-me-apart",
    author: "Cam L. Toe",
    genres: ["Biography", "Love Story"],
    id: 14,
    img: "https://images.squarespace-cdn.com/content/v1/55b0ec33e4b07fa072cd915c/1619648967568-UCEVX552O3ATATPO57IF/TMA+Paperback+bookshot.png",
    name: "Take Me Apart",
    price: 69,
    rating: 7,
    review: 153,
  },
  {
    pathname: "the-shape",
    author: "Buster Hyman",
    genres: ["Horror", "Thriller"],
    id: 15,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0GOYscjf6Nibbz_BocDtdvB0GVdC2CDloTQ&usqp=CAU",
    name: "The Shape",
    price: 77,
    rating: 8.5,
    review: 234,
  },
  {
    pathname: "sin-eater",
    author: "Phil Harmonic",
    genres: ["Biography", "Thriller"],
    id: 16,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling5.jpg",
    name: "Sin Eater",
    price: 32,
    rating: 3.2,
    review: 103,
  },
  {
    pathname: "transformation",
    author: "Otto Matic",
    genres: ["Horror", "Biography"],
    id: 17,
    img: "https://books.forbes.com/wp-content/uploads/2023/04/The-Great-Digital-Transformation-e1681138709476-922x1024.png",
    name: "Transformation",
    price: 72,
    rating: 5.5,
    review: 167,
  },
  {
    pathname: "the-boy",
    author: "Juan Annatoo",
    genres: ["Thriller", "Biography"],
    id: 18,
    img: "https://i.shgcdn.com/6cc86aa4-66d8-41b1-ad12-2029db30ed79/-/format/auto/-/preview/3000x3000/-/quality/lighter/",
    name: "The Boy",
    price: 100,
    rating: 9.5,
    review: 129,
  },
  {
    pathname: "moon-dance",
    author: "Cam L. Toe",
    genres: ["Horror", "Biography"],
    id: 19,
    img: "https://preview.colorlib.com/theme/abcbook/assets/img/gallery/best_selling1.jpg",
    name: "Moon Dance",
    price: 86,
    rating: 6,
    review: 130,
  },
  {
    pathname: "fated-hearts",
    author: "Buster Hyman",
    genres: ["Horror", "Love Story"],
    id: 20,
    img: "https://skyemalone.com/wp-content/uploads/2022/02/FatedHearts-Single-Paperback-CROPPED.png",
    name: "Fated Hearts",
    price: 150,
    rating: 10,
    review: 134,
  },
];

export type MovieType = {
  pathname: string;
  author: string;
  genres: string[];
  id: number;
  img: string;
  name: string;
  price: number;
  rating: number;
  review: string;
};

export type CarouselTypes = {
  banner: string;
  title: string;
  author: string;
  rating: number;
  review: number;
  price: number;
  pathname: string;
  genres: [];
  id: number;
  img: string;
  name: string;
  director: string;
};
